// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETHTPS.Data.Integrations.MSSQL;

public partial class UserFeedback
{
    public int Id { get; set; }

    public int Type { get; set; }

    public string Title { get; set; }

    public string Details { get; set; }

    public string ExtraData { get; set; }
}