version: '3.4'

services:
  ethtps.taskrunner:
    image: ${DOCKER_REGISTRY-}ethtpstaskrunner
    build:
      context: .
      dockerfile: ETHTPS.HangfireRunner/Dockerfile

  ethtps.api:
    image: ${DOCKER_REGISTRY-}ethtpsapi
    build:
      context: .
      dockerfile: ETHTPS.API/Dockerfile

