version: '3'

services:
  ethtps.taskrunner:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  ethtps.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

